name: Test script
on:
  # - push
  - pull_request
jobs:
  add-link-on-pr:
    name: Script  ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      
      - run: echo hello > ~/world.txt
      - uses: actions/upload-artifact@v2
        with:
          path: ~/world.txt
      
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: 'my-artifact'
          path: ~/world.txt

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      
      
      - name: comment on PR with link
        uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var BRANCH_NAME = process.env.BRANCH_NAME;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `https://mybinder.org/v2/gh/${context.repo.owner}/${context.repo.repo}/${BRANCH_NAME} :point_left: `
            })