name: Test script
on:
  # - push
  - pull_request
jobs:
  add_link_on_pr:
    name: Script  ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2

      - run: mkdir artifacts
      - name: Github Action for wget
        uses: wei/wget@v1.1.1
        with:
          args: -O artifacts/lenses_and_learners.pdf https://arxiv.org/pdf/1903.03671.pdf 

      - run: |
           echo hello > artifacts/world.pdf            
           ls -l artifacts/

      - uses: actions/upload-artifact@v2
        with:
          name: exquisit-artifact
          path: 'artifacts/*.pdf'

      - uses: actions/upload-artifact@v2
        with:
          name: lenses_and_learners.pdf
          path: 'artifacts/lenses_and_learners.pdf'
      
      - name: comment on PR with link to artifacts
        uses: actions/github-script@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var BRANCH_NAME = process.env.BRANCH_NAME;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${GITHUB_RUN_ID}#artifacts`
            })